apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: rdieleman/auth
      context: auth
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          target: dev
    - image: rdieleman/client
      context: client
      sync:
        manual:
          - src: '**/*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          target: dev
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
deploy:
  kubectl: { }
