name: test-shelf

on:
  pull_request:
    paths:
      - 'shelf/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd shelf && npm install && npm run test:ci
